from __future__ import annotations

from pathlib import Path

from rag_langgraph.constants import (
    CONFIG_DIR_NAME,
    DATA_DIR_NAME,
    DATABASE_DIR_NAME,
    ENV_FILE_NAME,
    MILVUS_COLLECTION_NAME,
    MODEL_CONFIG_YAML_PATH,
    MODEL_YAML_FILE_NAME,
    MODEL_YAML_PATH,
    NEP_DB_RELATIVE_PATH,
    NEP_PDF_RELATIVE_PATH,
    NOTEBOOKS_DIR_NAME,
    REVIEWS_CSV_RELATIVE_PATH,
    SCRIPTS_DIR_NAME,
    SRC_DIR_NAME,
)
from rag_langgraph.utils.get_root import PROJECT_ROOT

# Project root path
ROOT_DIR: Path = PROJECT_ROOT

# Top-level directory paths
CONFIG_DIR: Path = ROOT_DIR / CONFIG_DIR_NAME
DATA_DIR: Path = ROOT_DIR / DATA_DIR_NAME
DATABASE_DIR: Path = ROOT_DIR / DATABASE_DIR_NAME
NOTEBOOKS_DIR: Path = ROOT_DIR / NOTEBOOKS_DIR_NAME
SCRIPTS_DIR: Path = ROOT_DIR / SCRIPTS_DIR_NAME
SRC_DIR: Path = ROOT_DIR / SRC_DIR_NAME

# YAML / configuration file paths
MODEL_CONFIG_PATH: Path = ROOT_DIR / MODEL_CONFIG_YAML_PATH
MODEL_YAML_PATH: Path = ROOT_DIR / MODEL_YAML_PATH
CONFIG_YAML_PATH: Path = ROOT_DIR / CONFIG_DIR_NAME / MODEL_YAML_FILE_NAME

# Environment file path
ENV_FILE_PATH: Path = ROOT_DIR / ENV_FILE_NAME
DOTENV_PATH: Path = ENV_FILE_PATH

# Data file paths
NEP_PDF_PATH: Path = ROOT_DIR / NEP_PDF_RELATIVE_PATH
REVIEWS_CSV_PATH: Path = ROOT_DIR / REVIEWS_CSV_RELATIVE_PATH

# Database file paths
NEP_DB_PATH: Path = ROOT_DIR / NEP_DB_RELATIVE_PATH
MILVUS_DB_PATH: Path = NEP_DB_PATH

# Vector store collection name
DEFAULT_COLLECTION_NAME: str = MILVUS_COLLECTION_NAME

__all__ = [
    "CONFIG_DIR",
    "CONFIG_YAML_PATH",
    "DATABASE_DIR",
    "DATA_DIR",
    "DEFAULT_COLLECTION_NAME",
    "DOTENV_PATH",
    "ENV_FILE_PATH",
    "MILVUS_DB_PATH",
    "MODEL_CONFIG_PATH",
    "MODEL_YAML_PATH",
    "NEP_DB_PATH",
    "NEP_PDF_PATH",
    "NOTEBOOKS_DIR",
    "PROJECT_ROOT",
    "REVIEWS_CSV_PATH",
    "ROOT_DIR",
    "SCRIPTS_DIR",
    "SRC_DIR",
]
